--- #YAML:1.0
name:                Acme-Tanasinn
version:             0.01
abstract:            Don't think. Feel and you'll be tanasinn.
license:             perl
author:              
    - Squeeks <squeek@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
